### ISSUE TITLE
The last buffername stays inactive at the StatusBar after :bdelete

### ISSUE THREAD

**Issue by kristjoc** [mengelbrecht/lightline-bufferline#51]
I have configured lightline and lightline-bufferline as following

set laststatus=2        " Always show statusline
let g:lightline = {
        \ 'colorscheme': 'nord',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'readonly' ], ['buffers'] ],
        \   'right': [ [ 'lineinfo' ],
        \              [ 'percent' ],
        \              [ 'chdir', 'filetype' ] ]
        \ },
        \ 'component_function': {
        \   'chdir': 'LightlineWorkingDir',
        \ },
        \ 'component_expand': {
        \   'buffers': 'lightline#bufferline#buffers'
        \ },
        \ 'component_type': {
        \   'buffers': 'tabsel'
        \ }
        \ }

let g:lightline#bufferline#show_number  = 1
let g:lightline#bufferline#filename_modifier = ':t'
let g:lightline#bufferline#shorten_path = 2
let g:lightline#bufferline#unnamed = ''
function! LightlineWorkingDir()
        let dir = fnamemodify(getcwd(), ":~:.")
  return dir
endfunction

autocmd BufLeave,BufDelete,BufWritePost,TextChanged,TextChangedI * call lightline#update()

Burffers are being showed at the StatusBar and Everything's working as it should. Howwver, when I have only one buffer active and I type :bd or :dw to delete the buffer, the buffername remains inactive at the StatusBar and the focus goes to the new No Name buffer. The zombie buffername goes away if I type :bd again or :call lightline#update(). Tried to automatically call lightline#update() on BufLeave but it does not work.

This does not happens when buffers are shown in tabline though.

**Comment by mengelbrecht** [comment]
Placing the buffers in the statusbar does not work well because the list is not updated as often as it is necessary by lightline.
Everytime the buffers function is called by lightline (even with the autocmd) the deleted buffer is still "listed" although `:bdelete` unlists the buffer. As you already noticed this only happens when the buffers are placed in the statusbar instead of the tabline.

I don't have a solution for this issue, however a workaround is possible.
You can define a custom command to delete a buffer and automatically update lightline afterwards.
With this workaround you can delete a buffer using `:Bx` instead of `:bdelete` and the bufferlist should be correctly updated:
```viml
function! DeleteBufferAndUpdateLightline()
  exe 'bdelete'
  call lightline#update()
endfunction

command Bx call DeleteBufferAndUpdateLightline()
```

**Comment by kristjoc** [comment]
Thanks! It works just fine!
Keep up the good work.

**Comment by mengelbrecht** [comment]
Thanks 😊
