### ISSUE TITLE
Only show bufferline when more than one buffer is open

### ISSUE THREAD

**Issue by justsharan** [mengelbrecht/lightline-bufferline#99]
When I first installed the plugin, the bufferline wasn't showing up. In the docs, it said to use `:set showtabline = 2` to make the bufferline show _always_, which does work for me.

However, I want it to only show up when there's more than one buffer open (so if I'm only working with one file, it should not be there... if I'm working with more than one, then it should). How can I do that? If I look at `:help showtabline`, it looks like setting it to `1` should accomplish this, but it's not

https://user-images.githubusercontent.com/53885408/147841649-33dfec85-9a94-4c4d-a63b-2193c4eaed03.mp4

.

**Comment by mengelbrecht** [comment]
The setting `showtabline` is from vim and has to be set to `2` to enable the bufferline (otherwise it will not be visible at all).
Then you can use the setting [`min_buffer_count`](https://github.com/mengelbrecht/lightline-bufferline#glightlinebufferlinemin_buffer_count) to show the bufferline only when a certain number of buffers are open.
In your case you can set it to `2` to hide the bufferline if only one buffer is open:
```viml
let g:lightline#bufferline#min_buffer_count = 2
```

**Comment by justsharan** [comment]
I see... that setting seems to work. Thanks for your help!
